# This is not a stable release. Known issues will be noted on the lines in
#   which they occur.

# This script assumes the current working directory is equivalent to 'mydir'

import glob
from PIL import Image
import numpy as np
import vtk
from vtk.util import numpy_support

tiffs = glob.glob('*.tif')
tif_reader = vtk.vtkTIFFreader()
tif_reader.SetFileName(tiffs[0])
x,y = tif_reader.GetOutput().GetDimensions()
# In this block, there is an issue with the last line: GetOutput() fails
#   because the tif.reader object is considered non-iterable, and
#   the function otherwise fails because too many values are there to unpack.

data_3d = np.zeros([x,y,len(tiffs)])

for i,p in enumerate(tiffs):
  tif_reader.SetFileName(tiffs[0])
  tif_reader.Update()
  img_data = tif_reader.GetOutput()
  data_3d[:,:,i] = numpy_support.vtk_to_numpy(img_data)
# In this block, the problem that arises is from an apparent typing error:
#   The variables i,p are implicitly cast as ints, but the compiler reads
#   them as tuples, causing the compiler to object to the indices' typing.

data_3d_vtk = numpy_support.numpy_to_vtk(data_3d)
# This may be buggy in a way I haven't been able to find yet -- but it should
#   save the 3D numpy array out.
